### ISSUE TITLE
Destruction Issue.

### ISSUE THREAD

**Issue by TheCamZone** [j0ach1mmall3/ItemCommand#11]
I downloaded ItemCommand to create a tag system where you can win a command item from a crate, then people could trade their tag or use it on themselves instead of just receiving it from the crate. I'm trying to make a command where if you click it, it gives you a permission. But when I click it, it does not remove the item or add the permission to the player. Any help?

Console error:
09.08 16:40:50 [Server] INFO ... 18 more
09.08 16:40:50 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-ae40327-5084899]
09.08 16:40:50 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
09.08 16:40:50 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
09.08 16:40:50 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
09.08 16:40:50 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
09.08 16:40:50 [Server] INFO at com.j0ach1mmall3.itemcommand.listeners.PlayerListener.onInteract(PlayerListener.java:41) ~[?:?]
09.08 16:40:50 [Server] INFO at com.j0ach1mmall3.itemcommand.listeners.PlayerListener.handleCommandItem(PlayerListener.java:98) ~[?:?]
09.08 16:40:50 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.event.server.ServerCommandEvent.isCancelled()Z
09.08 16:40:50 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
09.08 16:40:50 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-ae40327-5084899]
09.08 16:40:50 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-ae40327-5084899]
09.08 16:40:50 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-ae40327-5084899]
09.08 16:40:50 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot.jar:git-Spigot-ae40327-5084899]
09.08 16:40:50 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot.jar:git-Spigot-ae40327-5084899]
09.08 16:40:50 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
09.08 16:40:50 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
09.08 16:40:50 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-ae40327-5084899]
09.08 16:40:50 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot.jar:git-Spigot-ae40327-5084899]
09.08 16:40:50 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot.jar:git-Spigot-ae40327-5084899]
09.08 16:40:50 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:694) [spigot.jar:git-Spigot-ae40327-5084899]
09.08 16:40:50 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:190) [spigot.jar:git-Spigot-ae40327-5084899]
09.08 16:40:50 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:194) [spigot.jar:git-Spigot-ae40327-5084899]
09.08 16:40:50 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:227) [spigot.jar:git-Spigot-ae40327-5084899]
09.08 16:40:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-ae40327-5084899]
09.08 16:40:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-ae40327-5084899]
09.08 16:40:50 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-ae40327-5084899]
09.08 16:40:50 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-ae40327-5084899]
09.08 16:40:50 [Server] INFO org.bukkit.event.EventException
09.08 16:40:50 [Server] ERROR Could not pass event PlayerInteractEvent to ItemCommand v1.5.4

Configuration: 
http://paste.ofcode.org/Mj3Y9udmUmQyucQAetkSrr
(Using the redeemtag command)

**Comment by j0ach1mmall3** [comment]
Server version?

**Comment by TheCamZone** [comment]
Running Spigot 1.8.6. 
I've tried multiple versions for the plugin, Not sure which one is right

**Comment by TheCamZone** [comment]
Do I just need to update my server version?

**Comment by j0ach1mmall3** [comment]
Probably yes

**Comment by TheCamZone** [comment]
Alright I will try that now.

**Comment by TheCamZone** [comment]
Ok, Thank you this fixed the error!
