### ISSUE TITLE
ERROR Could not pass event PlayerInteractEvent to ItemCommand v1.5.4

### ISSUE THREAD

**Issue by verocsgo** [j0ach1mmall3/ItemCommand#13]
`27.08 22:49:49 [Server] ERROR Could not pass event PlayerInteractEvent to ItemCommand v1.5.4
27.08 22:49:49 [Server] INFO org.bukkit.event.EventException
27.08 22:49:49 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot-1.7.10.jar:git-Spigot-1649]
27.08 22:49:49 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot-1.7.10.jar:git-Spigot-1649]
27.08 22:49:49 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [Spigot-1.7.10.jar:git-Spigot-1649]
27.08 22:49:49 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [Spigot-1.7.10.jar:git-Spigot-1649]
27.08 22:49:49 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:242) [Spigot-1.7.10.jar:git-Spigot-1649]
27.08 22:49:49 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:212) [Spigot-1.7.10.jar:git-Spigot-1649]
27.08 22:49:49 [Server] INFO at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:636) [Spigot-1.7.10.jar:git-Spigot-1649]
27.08 22:49:49 [Server] INFO at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:50) [Spigot-1.7.10.jar:git-Spigot-1649]
27.08 22:49:49 [Server] INFO at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.handle(PacketPlayInBlockPlace.java:86) [Spigot-1.7.10.jar:git-Spigot-1649]
27.08 22:49:49 [Server] INFO at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [Spigot-1.7.10.jar:git-Spigot-1649]
27.08 22:49:49 [Server] INFO at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [Spigot-1.7.10.jar:git-Spigot-1649]
27.08 22:49:49 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [Spigot-1.7.10.jar:git-Spigot-1649]
27.08 22:49:49 [Server] INFO at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [Spigot-1.7.10.jar:git-Spigot-1649]
27.08 22:49:49 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [Spigot-1.7.10.jar:git-Spigot-1649]
27.08 22:49:49 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [Spigot-1.7.10.jar:git-Spigot-1649]
27.08 22:49:49 [Server] INFO at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [Spigot-1.7.10.jar:git-Spigot-1649]
27.08 22:49:49 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.event.server.ServerCommandEvent.isCancelled()Z
27.08 22:49:49 [Server] INFO at com.j0ach1mmall3.itemcommand.listeners.PlayerListener.handleCommandItem(PlayerListener.java:98) ~[?:?]
27.08 22:49:49 [Server] INFO at com.j0ach1mmall3.itemcommand.listeners.PlayerListener.onInteract(PlayerListener.java:41) ~[?:?]
27.08 22:49:49 [Server] INFO at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source) ~[?:?]
27.08 22:49:49 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_79]
27.08 22:49:49 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_79]
27.08 22:49:49 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[Spigot-1.7.10.jar:git-Spigot-1649]
27.08 22:49:49 [Server] INFO ... 15 more`

**Comment by verocsgo** [comment]
Thanks for any assistance :)

**Comment by j0ach1mmall3** [comment]
What server version?

**Comment by verocsgo** [comment]
1.7.10
