### ISSUE TITLE
Disable worlds option

### ISSUE THREAD

**Issue by Elioz** [j0ach1mmall3/ItemCommand#3]
Hello,

There is an option to disable itemcommand in some worlds?
If no, this option can be added in the next version?

Thanks.

**Comment by j0ach1mmall3** [comment]
Don't give them the item?
Don't give them the permission to use the item in that world?
Don't give them the permission to use the command in that world?
That's 3 different ways, is that not enough?

**Comment by Elioz** [comment]
Second option seems to be fine, thanks.
