### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by droodzor** [j0ach1mmall3/ItemCommand#4]
Hey so i just got your plugin and want to warp players using a key to certain locations the command i use to warp the player is 
'[console] warp desertdungeon %playername%'
However it just says in the console that the command is unknown please type /help. I thought the plugin worked with all commands on your server or is it just vanilla

**Comment by droodzor** [comment]
Sorry for all the changes i found out that its because i had placeholder api on my server which does not work with your jlib pluguin and the other change is because its not only warps that arnt working its all commands including vanilla ones.

**Comment by MrDip** [comment]
bump commands dont seem to be working for me either.

**Comment by j0ach1mmall3** [comment]
Fixed in latest build
