### ISSUE TITLE
the plugin dose not pull the lib data

### ISSUE THREAD

**Issue by dgibbs3196** [j0ach1mmall3/ItemCommand#6]
well we was trying to get the plugin to to run.<p>
 [console] give %player_name% 54 1<p>
and the it not give out the items.<p>
but when I run <p>
 [op] i 54 1 it give them the items..<p>
The %player_name% is not working I have all the plugins online but it still don't wann work..

**Comment by j0ach1mmall3** [comment]
Do you have the placeholderapi player hook?
