### ISSUE TITLE
Issus & Suggestions

### ISSUE THREAD

**Issue by olesien** [j0ach1mmall3/ItemCommand#7]
Hello!
So first off, I have an issue with ItemCommand:
the command on click feature doesn't work.. It worked fine before, then it just randomly stopped worked... ;/ I am pretty sure this isn't your fault, but I don't really know the cause.. We have DrugMeUp installed (For non-rare drugs), and then we use ItemCommand for the rare drugs. Can they like.. Conflict with each other? Help pls :)
Information:
Plugins: https://gyazo.com/b01fe9e93cc6ac6148d2c4b95da6a843
Console log: http://pastebin.com/6QqCgwr5

Suggestions:
For first a [message] feature, that directly messages the player, instead of using /msg (it should only be pure text, no [Console -> Me] )
Also,
could you add a setting in each Itemcommand that either sets the item as.. Can-Only-Be-Brought-By-Command to true (as it is now)
or, if it is set to false, every item that for example is stone will be that command item? The option name should ofc not be that, but the same feature? (So that I can remove DrugMeUp lol)
Thanks! :)

Best regards,
olesien

**Comment by olesien** [comment]
Could you please answer?.. I have been waiting of a long time now.
If you wont answer in the next 48 hours, I will give this plugin a bad Review which none of us wants.

**Comment by j0ach1mmall3** [comment]
I might think about the first one, but the second one won't happen

**Comment by olesien** [comment]
But the bug?

**Comment by j0ach1mmall3** [comment]
I'll test the plugin again, in 4 days, when I'm back

**Comment by olesien** [comment]
Seems to be an error with the command.
Neither
        - '[console] effect %clicked% 8 120 2'
nor 
        - '[console] effect %player% 8 120 2'
works.. ;*(

**Comment by olesien** [comment]
ffs nvm.. It was PlaceholderAPI that was causing this.

**Comment by olesien** [comment]
Also, could you please add a /ic list feature?!?! It would help very much.
Thanks :)

**Comment by j0ach1mmall3** [comment]
Probably not
