### ISSUE TITLE
Give an item when when a player join the server

### ISSUE THREAD

**Issue by wedza** [j0ach1mmall3/ItemCommand#9]
Hello,

I've just installed your plugin who looks awesome and very lightweight and I have no issue with him !

My question is : **Can I give one of an item when a player first join my server ?**

I have already a essentials kit that is given for the newbies but I think I cannot give one of ItemCommand.
The other solution would be to execute a command automatically when a player joins the server, but I would like to know if there is any other solution for searching a new plugin...

Thank you very much ! My servers members are very happy with the new features that your plugin bring. :smiley:

**Comment by j0ach1mmall3** [comment]
That's not the purpose of this plugin, use an other plugin for that, sorry
